apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: nextepc-webui
spec:
  selector:
    matchLabels:
      app: nextepc-webui
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: nextepc-webui
    spec:
      containers:
      - name: nextepc-webui
        image: cewuandy/nextepc-webui
        ports:
        - containerPort: 3000
---
kind: Service
apiVersion: v1
metadata:
  name: nextepc-webui-service
spec:
  selector:
    app: nextepc-webui
  ports:
  - protocol: TCP
    port: 3000
    nodePort: 30001
  type: NodePort
